// components/Footer.vue
<script lang="ts" setup>
defineProps<{
  intro?: boolean;
}>();

const route = useRouter().currentRoute;
</script>

<template>
  <section
    v-if="!intro && route.path !== '/gallery'"
    class="flex flex-col items-center py-16 text-center px-4"
  >
    <h1 class="font-semibold text-2xl sm:text-3xl lg:text-4xl">Want to explore more?</h1>
    <p class="font-light mt-2">Learn more about me, myself and I.</p>
    <div class="flex sm:flex-row gap-4 mt-4">
      <NuxtLink class="btn btn-primary" to="/gallery"> View Photos </NuxtLink>
      <NuxtLink class="btn btn-outline" to="/projects"> Read Projects </NuxtLink>
    </div>
  </section>
  <footer class="relative w-full bg-background-100">
    <div class="mx-auto max-w-7xl px-6 md:px-8 py-12">
      <div class="flex flex-col md:flex-row md:justify-between">
        <div class="flex flex-col">
          <h1 class="text-xl">BombayTech</h1>
          <p class="mt-0.5 text-sm md:text-base">If you can imagine it, you can create it.</p>
          <div class="flex items-center gap-x-3 mt-2 fill-primary-800">
            <NuxtLink to="https://www.instagram.com/mau_bomb/" target="_blank">
              <Icon
                icon="instagram"
                className="fill-primary-800 hover:fill-primary-700 transition-colors duration-200"
              />
            </NuxtLink>
            <NuxtLink to="https://github.com/BombayV" target="_blank">
              <Icon
                icon="github"
                className="fill-primary-800 hover:fill-primary-700 transition-colors duration-200"
              />
            </NuxtLink>
            <NuxtLink to="/https://www.linkedin.com/in/mauricio-riveraperez/" target="_blank">
              <Icon
                icon="linkedin"
                className="fill-primary-800 hover:fill-primary-700 transition-colors duration-200"
              />
            </NuxtLink>
          </div>
        </div>
        <div class="flex flex-col md:flex-row md:gap-x-12 gap-y-2 mt-6 md:mt-0">
          <div class="flex flex-col">
            <h2>MAIN</h2>
            <TextLink to="/apps">Apps</TextLink>
            <TextLink to="/gallery">Gallery</TextLink>
            <TextLink to="/contact">Contact</TextLink>
          </div>
          <div class="flex flex-col">
            <h2>OTHER</h2>
            <TextLink to="/apps">Apps</TextLink>
            <TextLink to="/gallery">Gallery</TextLink>
            <TextLink to="/contact">Contact</TextLink>
          </div>
        </div>
      </div>
    </div>
    <div class="relative max-w-7xl mx-auto">
      <p class="border-t border-t-background-950 mx-6 md:mx-8 py-6">&copy; 2023 BombayTech</p>
    </div>
  </footer>
</template>

// src/lib/components/layout/Footer.svelte
<script lang="ts">
	import { ExternalLink, Github, Instagram, Linkedin, Sticker } from '@lucide/svelte';
	import Link from '$lib/components/global/link.svelte';

	const lastUpdated = '2025-12-02T12:00:00Z';
</script>

<footer
	class="flex w-full flex-col gap-y-8 border-t border-t-black/10 px-6 py-8 md:px-10 md:pt-16 dark:border-t-white/10"
>
	<div class="mx-auto w-full max-w-5xl px-6 md:px-8 lg:px-12">
		<div class="flex w-full justify-between">
			<div>
				<Sticker class="size-14 drop-shadow-sm" />
				<p class="mt-2 text-base font-medium tracking-wide md:text-lg">
					Mauricio Sebastian Rivera Perez
				</p>
				<p class="text-sm text-neutral-600 drop-shadow-sm md:text-base dark:text-neutral-400">
					If you can imagine it, you can create it.
				</p>
			</div>
			<div class="flex gap-x-16">
				<div class="flex flex-col gap-y-4">
					<h2 class="text-xs font-medium uppercase text-neutral-500">Contact</h2>
					<Link href="mailto:me@bombayv.com">
						<span class="flex items-center justify-center gap-x-1">
							Email
							<ExternalLink class="mb-0.5 size-4" />
						</span>
					</Link>
				</div>
				<div class="flex flex-col gap-y-4">
					<h2 class="text-xs font-medium uppercase text-neutral-500">Main</h2>
					<Link href="/">About</Link>
					<Link href="/gallery">Gallery</Link>
					<Link href="/portfolio">Portfolio</Link>
					<Link href="/contact">Contact</Link>
				</div>
			</div>
		</div>
		<div class="mt-16 flex flex-col items-center">
			<span
				class="mb-6 h-0.5 max-w-sm rounded-full bg-neutral-400/50 md:w-40 dark:bg-neutral-400/50"
			></span>
			<p class="text-sm dark:text-neutral-300">
				&copy; 2021 - {new Date().getFullYear()} Mauricio Sebastian Rivera Perez. All rights reserved.
			</p>
			<p class="text-xs text-neutral-500 dark:text-neutral-400">
				Last updated: {new Date(lastUpdated).toLocaleDateString()}
			</p>
		</div>
	</div>
</footer>
